site_name: Cinder


theme:
  name: null
  custom_dir: cinder
  colorscheme: github
  highlightjs: true

nav:
  - Home: index.md
  - Specimen: specimen.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
